### ISSUE TITLE
Dataset link is broken

### ISSUE THREAD

**Issue by vevenom** [skanti/SceneCAD#1]
Hi,

I was trying to download your layout dataset but the link appears to be broken. Can you please update the link?

Thanks.

**Comment by skanti** [comment]
Hi :)
sorry, i'll fix it asap

**Comment by vevenom** [comment]
Hi,

is there any update for when the dataset will be available again?

Thanks.

**Comment by skanti** [comment]
fixed the broken link, sorry :)
